changed from python to python3
the python command gives this error
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    import setuptools
ImportError: No module named setuptools